name: flutter_module
description: A new flutter module project.
version: 1.0.0+1

dependencies:
  package_info:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  module:
    androidPackage: com.example.fluttermodule
